Module5 task1
htmlacademy-adaptive/1481797-cat-energy-21 pull request #11
Opened 2020-12-09 01:14 UTC by qirex93

2020-12-09 18:25 UTC, vovaborisenko requested changes
# ОЧЕНЬ ПРИЯТНО УДИВЛЕН, ЧТО ВСЕ ТАК ХОРОШО ПО PIXEL PERFECT. МОЛОДЕЦ!!!!

есть пару советов, замечаний:
- в десктопной версии при ширине экрана больше, чем desctop-width, нужно чтобы ширина контента оставалась той же, что и на макете (должны появится "уши", о них говорили в лайве к этому модулю). ты зря wrapper'ы убрал.
- в мобильной версии фото кота не должно так растягиваться. пропорции кота должны остаться.
![image](https://user-images.githubusercontent.com/30496847/101666738-a20d0b00-3a5f-11eb-81bc-2ccbf76e92f0.png)
- вот это поправь в мобильной и планшетной версиях:
![image](https://user-images.githubusercontent.com/30496847/101667301-38413100-3a60-11eb-9908-f6dfb4824b6f.png)
- и это
![image](https://user-images.githubusercontent.com/30496847/101667163-0cbe4680-3a60-11eb-89a8-92b07c674295.png)
- не нужно так ограничивать текст
![image](https://user-images.githubusercontent.com/30496847/101667768-c9b0a300-3a60-11eb-9b8b-6d34b5fb7b07.png)

2020-12-09 18:25 UTC, vovaborisenko commented on source/index.html
> +      </button>
![image](https://user-images.githubusercontent.com/30496847/101668352-7e4ac480-3a61-11eb-9f1e-22270f741280.png)

2020-12-09 18:25 UTC, vovaborisenko commented on source/index.html
> +              </object>
лучше использовать svg, с этими объектами ты никакие манипуляции не сделаешь

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/advantage.less
> +    }
если тебе нужны эти модификаторы только для числа, то и назвать их лучше числами

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/contacts.less
> +  margin-left: 2px;
в таких случаях лучше писать `margin: 3px 0 0 2px;`

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/copyright.less
> +  width: 100%;
неправильный порядок css свойств

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/description.less
> +    padding-bottom: 15px;
нужно переписать в одно свойство

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/diets.less
>    }
указывать отрицательные внешние отступы не стоит, т.к. это не позволит тебе переиспользовать блок `diets`. Лучше блоку `page-header` добавь класс элемента блока `page` (например: `page__header`). и этому элементу задай в декстопе `position: absolute`.

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/live-example.less
> +  }
неправильный порядок css свойств

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/live-example.less
> +  }
неправильный порядок css свойств

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/live-example.less
> +  }
неправильный порядок css свойств

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/results.less
> +  margin-top: 15px;
перепиши, пожалуйста, во всем проекте вот такие строки в одну строку. поддерживать такой код сложно

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/blocks/diets.less
>    }
и еще в нескольких местах есть отрицательные margin'ы, постарайся от них избавиться.

2020-12-09 18:25 UTC, vovaborisenko commented on source/less/global/variables.less
> +  --basic-green-2: #5eaa2f;
basic-green-2 - такая переманная мало информативная. используй добавки: ярче светлее темнее, или второстепенный, первичный, акцентный

2020-12-09 18:32 UTC, qirex93 commented on source/less/global/variables.less
> +  --basic-green-2: #5eaa2f;
)) такая в макете) ок

2020-12-09 18:34 UTC, qirex93 commented on source/index.html
> +              </object>
давай оставим до дз по графике, вставлял их чтоб полотна не было в коде

2020-12-11 20:26 UTC, qirex93 commented on source/less/blocks/diets.less
>    }
почему блоку page-header, ты наверно имел ввиду diets__header

2020-12-11 23:51 UTC, qirex93 commented on source/less/blocks/diets.less
>    }
если я так делаю наверху пробел будет, который надо както убрать

2020-12-12 18:16 UTC, vovaborisenko requested changes
### по БЭМ блокам нельзя задавать внешние отступы и position: absolute, sticky, (a также z-index) для этого существуют элементы. исправь это, пожалуйста, для всех блоков. блок не должен ничего знать о внешнем расположении.

- и еще:
![image](https://user-images.githubusercontent.com/30496847/101991625-227d7700-3cbf-11eb-9ae1-1f309c91e2ef.png)

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/advantage.less
>  }
блоку нельзя задавать внешних отступов

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/advantage.less
> +  }
блоку нельзя задавать внешних отступов

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/catalog-type.less
> +  }
блоку нельзя задавать внешние отступы

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/contacts.less
> +  }
селектор не по БЭМ

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/contacts.less
> +    min-width: 425px;
блок не может иметь position: absolute

2020-12-12 18:16 UTC, vovaborisenko commented on source/less/blocks/site-list.less
> +    min-width: 479px;
блоку нельзя задавать внешние отступы

2020-12-13 07:16 UTC, vovaborisenko reviewed
# Отличная работа, молодец

2020-12-13 07:17 UTC, merged