Module5 task3
htmlacademy-adaptive/1481797-cat-energy-21 pull request #13
Opened 2020-12-21 01:05 UTC by qirex93

2020-12-21 16:12 UTC, vovaborisenko requested changes
# по pixelperfecr все замечательно, молодец!!

- по БЭМ нужно писать селекторы с минимальной специфичностью допускается увеличение специфичности только при добавлении модификатора). Избавься везде от излишней специфичности.
- и вот несколько скрино, по которым нужно сделать правки.
![2020-12-21_18-31-05](https://user-images.githubusercontent.com/30496847/102797102-411af680-43c0-11eb-8f23-6414da7e765f.jpg)
![2020-12-21_18-37-11](https://user-images.githubusercontent.com/30496847/102797119-48da9b00-43c0-11eb-93db-6c558bb41093.jpg)
![2020-12-21_18-47-56](https://user-images.githubusercontent.com/30496847/102797142-54c65d00-43c0-11eb-9983-32b09fecc3a4.jpg)

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +    }
от этих модификаторов нужно избавиться

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +    margin-left: 36px;
зачем тебе такая вложенность?

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +  }
зачем тебе такакя вложенность?

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +    }
такой вложенности быть не должно

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +      bottom: 225px;
лучше задать позиционирование через calc(100% - `число`px)

2020-12-21 16:12 UTC, vovaborisenko commented on source/less/blocks/product.less
> +      }
такой вложенности быть не должно

2020-12-23 16:25 UTC, qirex93 commented on source/less/blocks/product.less
> +    }
сделал авто снизу и сверху маржинами - так как хз как там равнять для перфекта - там в мобильной версии - фотки накиданы произвольно

2020-12-24 18:44 UTC, vovaborisenko commented
# Все замечательно

2020-12-24 18:44 UTC, merged