Module3 task3
htmlacademy-adaptive/1481797-cat-energy-21 pull request #7
Opened 2020-11-24 22:56 UTC by qirex93

стили для каталога

2020-11-25 16:00 UTC, vovaborisenko requested changes
### хорошая работа!!

не стоит забывать, что у блоков не может быть внешних отступов. для этого существуют элементы.

2020-11-25 18:24 UTC, qirex93 commented on source/less/blocks/gift.less
> +}
сделал wrapper

2020-11-25 18:35 UTC, qirex93 commented on source/less/blocks/product.less
> +}
убрал в кнопку

2020-11-25 18:53 UTC, qirex93 commented on source/less/blocks/product.less
> +}
сделал вложенность

2020-11-25 19:04 UTC, qirex93 commented on source/less/blocks/sub-product.less
> +}
сделал вложенность

2020-11-25 19:10 UTC, qirex93 commented on source/less/blocks/sub-products.less
> +}
убрал в див

2020-11-26 03:42 UTC, vovaborisenko commented on source/less/blocks/gift.less
> +}
не очень хорошее решение. лучше создавать внешнюю обертку, у которой будут внешние отступы

2020-11-26 03:45 UTC, merged