Module4 task1
htmlacademy-adaptive/1481797-cat-energy-21 pull request #8
Opened 2020-11-30 15:42 UTC by qirex93

2020-11-30 17:01 UTC, vovaborisenko requested changes
## с сетками почти везде все хорошо.

- подумай над блоком `diets`: в планшетной и десктопной версиях картинку продукта можно задать через `position: absolute` и тогда не нужно ее делать через background в платшете, а в дектопе извращаться над флексами.
- задавать фиксированные размеры для `diets__wrapper` тоже не следует (хотя бы тогда используй min-height, но можно и без него обойтись);
- не сделано меню в адаптивных версиях;
- в less нет единого порядка следования css свойcтв;
- **и совет**: медиа запросы могут быть вложенными, например
вместо:
```
.map iframe {
  width: 100%;
}

@media (min-width: @tablet-width) {
  .map iframe {
    height: 400px;
  }
}
```
можно написать:
```
.map iframe {
  width: 100%;

    @media (min-width: @tablet-width) {
        height: 400px;
    }
}
```
такие изменения можно произвести по всем файлам `.less`.

2020-11-30 21:02 UTC, qirex93 commented on source/less/blocks/catalogs-list.less
>  }
поменял

2020-11-30 21:22 UTC, qirex93 commented
> * **и совет**: медиа запросы могут быть вложенными, например
>   вместо:
> 
> ```
> .map iframe {
>   width: 100%;
> }
> 
> @media (min-width: @tablet-width) {
>   .map iframe {
>     height: 400px;
>   }
> }
> ```
> 
> можно написать:
> 
> ```
> .map iframe {
>   width: 100%;
> 
>     @media (min-width: @tablet-width) {
>         height: 400px;
>     }
> }
> ```
> 
> такие изменения можно произвести по всем файлам `.less`.

во всех типо в diets.less, мне удобней отдельно для разрешений стили писать

2020-12-01 08:48 UTC, vovaborisenko reviewed
# все хорошо!!!

2020-12-01 08:48 UTC, merged